### ISSUE TITLE
Figure out a way to incorporate other apps (CORS issues etc.)

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-portal#6]
Help each respective service team set up their apps to be included "under" the navbar (CORS etc.)

- [x] https://github.com/unity-sds/unity-ui/issues/19
- [x] https://github.com/unity-sds/unity-sds-portal/issues/10
- [x] https://github.com/unity-sds/unity-ui/issues/22

**Comment by rtapella** [comment]
part of https://github.com/unity-sds/unity-project-management/issues/74

**Comment by rtapella** [comment]
also get Airflow working inside Navbar

**Comment by rtapella** [comment]
dependencies are 24.1.5... so this cannot be done before that

**Comment by rtapella** [comment]
Start with Airflow (#22 )

**Comment by anilnatha** [comment]
@galenatjpl The reason we have had CORS issues in the past is because the services we were loading into the UI were being served from URLs that weren't part of the same domain, i.e. not routed through the venue's CloudFront instance.

Assuming that the service areas will be using a venue's cloudfront instance to provide access to their respective user facing UI (dockstore, stac browser, airflow, etc.), won't CORS issue be a moot point?

**Comment by galenatjpl** [comment]
@anilnatha , Both @ramesh-maddegoda and @mike-gangl were working on a httpd server that has a ALB and cert.  I think @mike-gangl was thinking that airflow is a "www" thing, and not an "api" thing, and therefore would go through httpd.

In other words,
www.* points to the httpd load balancers
api.* points to API Gateways

So the other apps (and the Navbar UI) should have URLs starting with https://www.dev.mdps.mcp.nasa.gov:4443/ ...

So I think the answer hopefully is that you don't have this CORS issue anymore, but we would have to test.

**Comment by mike-gangl** [comment]
There may still be some CORS issues to resolve, e.g. submitting a job to the API (WPS)  from the dashboard, but i think those belonging to the same domain will help alleviate these issues.

As for hosting another application, its essentially an iframe pointing at www... content, so that should be pretty standard.

**Comment by rtapella** [comment]
needs u-cs work on httpd resolved

**Comment by rtapella** [comment]
May need to handle the APIs because they'll have a different domain (api.blah vs. www.blah) when loading the Jobs Dashboard (for example)

**Comment by rtapella** [comment]
@anilnatha I think we can test Jupyter in the navbar now... it should have a URL that can avoid the CORS stuff

**Comment by rtapella** [comment]
also need to handle passing of Cognito tokens into the iframe

**Comment by rtapella** [comment]
Cognito into iframe = cookies. Working on it

**Comment by rtapella** [comment]
Each health-endpoint URL should have the MCP URL
then it should show up in the navbar and work properly

**Comment by rtapella** [comment]
calling this done with the isPortalIntegrated work
